### ISSUE TITLE
LaTeX support for SymPy outputs

### ISSUE THREAD

**Issue by pyRobShrk** [gzuidhof/starboard-python#1]
One of the really nice things about SymPy in Jupyter is the repr of all SymPy objects can output nice looking math with [LaTeX (via MathJax)](https://docs.sympy.org/latest/tutorial/printing.html).

**Comment by gzuidhof** [comment]
I had a look into SymPy, I think it should be possible to get it to work - but we need to wait for a new release of Pyodide.

As long as somehow we can convince Sympy to output classes that have a `_repr_latex_()` function defined, we can check for its presence like we do [here](https://github.com/gzuidhof/starboard-python/blob/master/src/index.ts#L158-L166), and then use KaTeX to render it.

After digging into the sympy source code, I realized that `_repr_latex()` will always be present - but only in later versions of SymPy (it took me a while to realize it changed so much). The current Pyodide release (0.15.0) ships with version SymPy v1.3 which is too old.

The newest version has been added to Pyodide master (10 days ago), but no release has been made yet that includes it. We could ask politely for a new minor release that includes the changes.


In a (non-ipython) Python shell:
```
>>> import sympy as s
>>> s.__version__
'1.6.2'
>>> s.symbols('x')._repr_latex_()
'$\\displaystyle x$'
```
And then after I downgraded to Pyodide's current version 1.3:
```
>>> import sympy as s
>>> s.__version__
'1.3'
>>> s.symbols('x')._repr_latex_()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Symbol' object has no attribute '_repr_latex_'
```

More advanced support which would also print primitive values in LaTeX style after calling `init_printing()` would require a bit more work - but are definitely possible.

**Comment by gzuidhof** [comment]
In the meantime you can define a visualization function `vis` like this:

![image](https://user-images.githubusercontent.com/1039510/97244006-6be93400-17ef-11eb-8593-85f9b95a73a1.png)

Notebook link: https://starboard.gg/nb/n9hDNTc
Curious what you will use Starboard for :)

**Comment by pyRobShrk** [comment]
That is awesome! Thank you. I think Starboard is going to make me learn a lot about JavaScript and web programming. There’s so much potential with Starboard; I can’t wait to see what people do with it.

**Comment by pyRobShrk** [comment]
This issue is partially-resolved with the update to pyodide 0.16. A sympy **Integral** automatically shows up rendered with katex, but a **Matrix** object does not.

**Comment by stefnotch** [comment]
@pyRobShrk Do you still happen to have a piece of code that reproduces this issue? Chances are that a Matrix object uses some special syntax that KaTeX doesn't understand out of the box.

**Comment by pyRobShrk** [comment]
@stefnotch Matrix representation seems to be working just fine now in Starboard 0.12 (pyodide 0.17).

**Comment by stefnotch** [comment]
@pyRobShrk Awesome to hear! I take it that this issue can be closed then?
If you stumble upon any other issues, feel free to open new issues
